# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-28 23:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_auto_20170626_1541'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='is_shipping_address',
        ),
    ]
