# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-03 04:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_remove_address_is_shipping_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email_address',
            field=models.EmailField(max_length=255, unique=True),
        ),
    ]
