# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-03 14:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_auto_20170703_0417'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='address_id',
            new_name='id',
        ),
    ]
