# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-03 23:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_auto_20170603_2152'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CreditCard',
        ),
    ]
