# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-22 04:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_order_orderitem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='orderitem',
            options={'managed': True},
        ),
        migrations.AlterModelTable(
            name='order',
            table='orders',
        ),
        migrations.AlterModelTable(
            name='orderitem',
            table='order_items',
        ),
    ]
