# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-22 20:21
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0009_auto_20170622_2015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date_ordered',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
