# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-25 22:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0013_auto_20170624_0402'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CreditCard',
        ),
    ]
