# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-25 22:58
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payments', '0014_delete_creditcard'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditCard',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cc_number', models.CharField(max_length=16)),
                ('security_code', models.CharField(max_length=3)),
                ('expiration', models.DateField()),
                ('provider', models.CharField(max_length=50)),
                ('name_on_card', models.CharField(max_length=150)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'managed': True,
                'db_table': 'credit_cards',
            },
        ),
    ]
