# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-26 22:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0016_creditcard_card_nickname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creditcard',
            name='card_nickname',
        ),
    ]
