# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-03 23:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20170603_2152'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='book',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='techvalleytime',
            options={'managed': True},
        ),
        migrations.AlterModelTable(
            name='author',
            table='authors',
        ),
        migrations.AlterModelTable(
            name='book',
            table='books',
        ),
        migrations.AlterModelTable(
            name='techvalleytime',
            table='tech_valley_times',
        ),
    ]
