# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-16 14:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='publish_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
