# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-16 15:57
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0011_auto_20170616_1545'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('review_id', models.AutoField(primary_key=True, serialize=False)),
                ('publish_date', models.DateField(default=django.utils.timezone.now)),
                ('user_rating', models.DecimalField(decimal_places=2, max_digits=3)),
                ('review_header', models.CharField(max_length=255)),
                ('review_body', models.TextField()),
                ('book', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.Book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'reviews',
                'managed': True,
            },
        ),
    ]
